# Generated by Django 4.2.2 on 2023-07-12 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_alter_product_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='files',
        ),
        migrations.RemoveField(
            model_name='product',
            name='images',
        ),
    ]
