# Generated by Django 4.2.2 on 2023-07-12 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0014_remove_product_images_product_image_urls'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='selected_image',
            field=models.CharField(blank=True, choices=[], max_length=100),
        ),
    ]
