# Generated by Django 4.2.2 on 2023-07-12 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0015_product_selected_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_urls',
        ),
        migrations.RemoveField(
            model_name='product',
            name='selected_image',
        ),
        migrations.AddField(
            model_name='product',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='product_images', to='ecommerce.productimage'),
        ),
    ]
