# Generated by Django 4.2.2 on 2023-07-12 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0018_product_is_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileupload',
            name='product',
        ),
        migrations.AddField(
            model_name='fileupload',
            name='name',
            field=models.CharField(default='ebook', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='file',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.fileupload'),
        ),
    ]
