# Generated by Django 4.2.2 on 2023-07-12 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0020_remove_fileupload_name_fileupload_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cover_image',
            field=models.IntegerField(default=0, max_length=10),
        ),
    ]
