# Generated by Django 4.2.2 on 2023-07-12 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0021_product_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cover_image',
            field=models.IntegerField(default=0),
        ),
    ]
