# Generated by Django 4.2.2 on 2023-07-17 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0022_alter_product_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='payment_link',
            field=models.CharField(default=''),
        ),
    ]
