# Generated by Django 4.2.2 on 2023-06-24 20:28

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_name',
            field=models.CharField(default=accounts.models.generate_unique_username, max_length=24, unique=True),
        ),
    ]
