# Generated by Django 4.2.2 on 2023-06-24 20:32

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_name',
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default=accounts.models.generate_unique_username, max_length=24, unique=True),
        ),
    ]
