# Generated by Django 4.2.2 on 2023-06-21 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0003_comment_author_email_comment_author_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='author_email',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='author_name',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='author_picture',
        ),
    ]
