# Generated by Django 4.2.2 on 2023-06-22 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0005_comment_author_email_comment_author_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='codesnippet',
            name='language',
            field=models.CharField(choices=[('python', 'Python'), ('javascript', 'Javascript')], default='javascipt', max_length=100),
        ),
    ]
