# Generated by Django 4.2.2 on 2023-06-22 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0006_codesnippet_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codesnippet',
            name='code_snippet',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='codesnippet',
            name='content',
            field=models.CharField(),
        ),
    ]
