# Generated by Django 4.2.2 on 2023-06-22 21:42

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0007_alter_codesnippet_code_snippet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codesnippet',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
    ]
